# EXAMPLE SCRIPT MENU ITEMS
EXAMPLE_DEM_MENU_ITEM = "Warp/Scripts/Example DEM"
EXAMPLE_MESH_MENU_ITEM = "Warp/Scripts/Example Mesh"
EXAMPLE_NVDB_MENU_ITEM = "Warp/Scripts/Example NVDB"
EXAMPLE_RAYCAST_MENU_ITEM = "Warp/Scripts/Example Raycast"
EXAMPLE_RAYMARCH_MENU_ITEM = "Warp/Scripts/Example Raymarch"
EXAMPLE_SIM_ANT_MENU_ITEM = "Warp/Scripts/Example Sim Ant"
EXAMPLE_SIM_CLOTH_MENU_ITEM = "Warp/Scripts/Example Sim Cloth"
EXAMPLE_SIM_GRAD_BOUNCE_MENU_ITEM = "Warp/Scripts/Example Sim Grad Bounce"
EXAMPLE_SIM_GRAD_CLOTH_MENU_ITEM = "Warp/Scripts/Example Sim Grad Cloth"
EXAMPLE_SIM_GRANULAR_MENU_ITEM = "Warp/Scripts/Example Sim Granular"
EXAMPLE_SIM_HUMANOID_MENU_ITEM = "Warp/Scripts/Example Sim Humanoid"
EXAMPLE_SIM_NEO_HOOKEAN_MENU_ITEM = "Warp/Scripts/Example Sim Neo Hookean"
EXAMPLE_SIM_PARTICLE_CHAIN_MENU_ITEM = "Warp/Scripts/Example Sim Particle Chain"
EXAMPLE_SIM_RIGID_CHAIN_MENU_ITEM = "Warp/Scripts/Example Sim Rigid Chain"
EXAMPLE_SIM_RIGID_CONTACT_MENU_ITEM = "Warp/Scripts/Example Sim Rigid Contact"
EXAMPLE_SIM_RIGID_FEM_MENU_ITEM = "Warp/Scripts/Example Sim Rigid FEM"
EXAMPLE_SIM_RIGID_FORCE_MENU_ITEM = "Warp/Scripts/Example Sim Rigid Force"
EXAMPLE_SIM_RIGID_GYROSCOPIC_MENU_ITEM = "Warp/Scripts/Example Sim Rigid Gyroscopic"
EXAMPLE_SIM_RIGID_KINEMATICS_MENU_ITEM = "Warp/Scripts/Example Sim Rigid Kinematics"
EXAMPLE_WAVE_MENU_ITEM = "Warp/Scripts/Example Wave"
EXAMPLE_BROWSE_MENU_ITEM = "Warp/Scripts/Browse"

# EXAMPLE SCRIPTS
EXAMPLE_DEM_SCRIPT = "example_dem.py"
EXAMPLE_MESH_SCRIPT = "example_mesh.py"
EXAMPLE_NVDB_SCRIPT = "example_nvdb.py"
EXAMPLE_RAYCAST_SCRIPT = "example_raycast.py"
EXAMPLE_RAYMARCH_SCRIPT = "example_raymarch.py"
EXAMPLE_SIM_ANT_SCRIPT = "example_sim_ant.py"
EXAMPLE_SIM_CLOTH_SCRIPT = "example_sim_cloth.py"
EXAMPLE_SIM_GRAD_BOUNCE_SCRIPT = "example_sim_grad_bounce.py"
EXAMPLE_SIM_GRAD_CLOTH_SCRIPT = "example_sim_grad_cloth.py"
EXAMPLE_SIM_GRANULAR_SCRIPT = "example_granular.py"
EXAMPLE_SIM_HUMANOID_SCRIPT = "example_humanoid.py"
EXAMPLE_SIM_NEO_HOOKEAN_SCRIPT = "example_neo_hookean.py"
EXAMPLE_SIM_PARTICLE_CHAIN_SCRIPT = "example_particle_chain.py"
EXAMPLE_SIM_RIGID_CHAIN_SCRIPT = "example_rigid_chain.py"
EXAMPLE_SIM_RIGID_CONTACT_SCRIPT = "example_rigid_contact.py"
EXAMPLE_SIM_RIGID_FEM_SCRIPT = "example_rigid_fem.py"
EXAMPLE_SIM_RIGID_FORCE_SCRIPT = "example_rigid_force.py"
EXAMPLE_SIM_RIGID_GYROSCOPIC_SCRIPT = "example_rigid_gyroscopic.py"
EXAMPLE_SIM_RIGID_KINEMATICS_SCRIPT = "example_kinematics.py"
EXAMPLE_WAVE_SCRIPT = "example_wave.py"

# EXAMPLE SCENE MENU ITEMS
SCENE_CLOTH_MENU_ITEM = "Warp/Scenes/Cloth"
SCENE_DEFORM_MENU_ITEM = "Warp/Scenes/Deform"
SCENE_PARTICLES_MENU_ITEM = "Warp/Scenes/Particles"
SCENE_WAVE_MENU_ITEM = "Warp/Scenes/Wave"
SCENE_BROWSE_MENU_ITEM = "Warp/Scenes/Browse"

# EXAMPLE SCENES
SCENE_CLOTH = "example_cloth.usd"
SCENE_DEFORM = "example_deform.usd"
SCENE_PARTICLES = "example_particles.usd"
SCENE_WAVE = "example_wave.usd"