# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Wavefront OBJ file format parser."""

from __future__ import annotations

# Standard library
import os

# Third-party
import numpy as np

from warp._src.io.mesh import MeshData, _apply_flip_winding


def read_obj(filename: str, flip_winding: bool = False) -> MeshData:
    """Read a mesh from an OBJ file.

    Supports:
    - Vertex positions (v)
    - Vertex normals (vn)
    - Texture coordinates (vt)
    - Face indices (f) with v, v/vt, v//vn, v/vt/vn formats
    - Quad and n-gon faces (auto-triangulated via fan)
    - Negative indices (relative to end of vertex list)
    - 1-indexed to 0-indexed conversion

    Args:
        filename: Path to the OBJ file.
        flip_winding: If True, reverse triangle winding order.

    Returns:
        MeshData containing points, indices, and optional normals/uvs.

    Raises:
        FileNotFoundError: If the file does not exist.
        RuntimeError: If the file contains no vertices or no faces.
    """
    if not os.path.exists(filename):
        raise FileNotFoundError(f"OBJ file not found: '{filename}'")

    points = []
    normals = []
    uvs = []
    indices = []

    with open(filename, encoding="utf-8") as f:
        for _line_num, line in enumerate(f, 1):
            line = line.strip()  # noqa: PLW2901
            if not line or line.startswith("#"):
                continue

            parts = line.split()
            if not parts:
                continue

            prefix = parts[0]

            if prefix == "v" and len(parts) >= 4:
                # Vertex position: v x y z [w]
                points.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif prefix == "vn" and len(parts) >= 4:
                # Vertex normal: vn nx ny nz
                normals.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif prefix == "vt" and len(parts) >= 3:
                # Texture coordinate: vt u [v] [w]
                uvs.append([float(parts[1]), float(parts[2])])
            elif prefix == "f":
                # Face: f v1 v2 v3 ... or f v1/vt1 v2/vt2 v3/vt3 ...
                face_verts = []
                for token in parts[1:]:
                    # Handle v, v/vt, v//vn, v/vt/vn
                    v_idx_str = token.split("/")[0]
                    if not v_idx_str:
                        continue
                    v_idx = int(v_idx_str)
                    # OBJ is 1-indexed; negative = relative to end
                    if v_idx < 0:
                        v_idx = len(points) + v_idx
                    else:
                        v_idx -= 1
                    face_verts.append(v_idx)

                # Fan triangulation for n-gons (n >= 3)
                if len(face_verts) >= 3:
                    for i in range(1, len(face_verts) - 1):
                        indices.extend([face_verts[0], face_verts[i], face_verts[i + 1]])

    if not points:
        raise RuntimeError(f"No vertices found in OBJ file: '{filename}'")
    if not indices:
        raise RuntimeError(f"No faces found in OBJ file: '{filename}'")

    points_array = np.array(points, dtype=np.float32)
    indices_array = np.array(indices, dtype=np.int32)
    # Only include normals/UVs if count matches vertices (per-vertex data required)
    # OBJ files can have different vn/vt count than v count for hard-edge meshes
    normals_array = np.array(normals, dtype=np.float32) if normals and len(normals) == len(points) else None
    uvs_array = np.array(uvs, dtype=np.float32) if uvs and len(uvs) == len(points) else None

    if flip_winding:
        indices_array, normals_array = _apply_flip_winding(indices_array, normals_array)

    return MeshData(
        points=points_array,
        indices=indices_array,
        normals=normals_array,
        uvs=uvs_array,
    )


def write_obj(
    points: np.ndarray,
    indices: np.ndarray,
    filename: str,
    normals: np.ndarray | None = None,
    uvs: np.ndarray | None = None,
) -> None:
    """Write a mesh to an OBJ file.

    Note: This function assumes normals and uvs are per-vertex and aligned
    with the points array (i.e., the same index is used for position,
    texture coordinate, and normal when emitting faces). OBJ 1-based
    indexing is applied automatically.

    Args:
        points: Vertex positions, shape (N, 3).
        indices: Triangle indices, shape (M * 3,).
        filename: Output file path.
        normals: Optional vertex normals, shape (N, 3). Must be aligned
            with points (same length, same indices).
        uvs: Optional texture coordinates, shape (N, 2). Must be aligned
            with points (same length, same indices).
    """
    with open(filename, "w", encoding="utf-8") as f:
        # Write header
        f.write("# OBJ file generated by Warp\n")
        f.write(f"# {len(points)} vertices, {len(indices) // 3} faces\n")

        # Write vertices
        for p in points:
            f.write(f"v {p[0]} {p[1]} {p[2]}\n")

        # Write texture coordinates
        if uvs is not None:
            for uv in uvs:
                f.write(f"vt {uv[0]} {uv[1]}\n")

        # Write vertex normals
        if normals is not None:
            for n in normals:
                f.write(f"vn {n[0]} {n[1]} {n[2]}\n")

        # Write faces (OBJ is 1-indexed)
        has_normals = normals is not None
        has_uvs = uvs is not None

        indices_reshaped = indices.reshape(-1, 3)
        for face in indices_reshaped:
            if has_normals and has_uvs:
                f.write(
                    f"f {face[0] + 1}/{face[0] + 1}/{face[0] + 1} "
                    f"{face[1] + 1}/{face[1] + 1}/{face[1] + 1} "
                    f"{face[2] + 1}/{face[2] + 1}/{face[2] + 1}\n"
                )
            elif has_uvs:
                f.write(f"f {face[0] + 1}/{face[0] + 1} {face[1] + 1}/{face[1] + 1} {face[2] + 1}/{face[2] + 1}\n")
            elif has_normals:
                f.write(f"f {face[0] + 1}//{face[0] + 1} {face[1] + 1}//{face[1] + 1} {face[2] + 1}//{face[2] + 1}\n")
            else:
                f.write(f"f {face[0] + 1} {face[1] + 1} {face[2] + 1}\n")
