name: Pull Request

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "debug/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
