# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Deploy Sphinx documentation to Pages

# Runs on every tag created beginning with the character v
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  PYTHONFAULTHANDLER: "1" # Dump tracebacks on fatal signals (SIGSEGV, SIGABRT, etc.)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
        with:
          version: "0.11.3"
      - name: Set up Python
        run: uv python install
      - name: Build Warp without CUDA Support
        run: |
          uv run build_lib.py --no-cuda
      - name: Build Sphinx documentation
        run: |
          uv run --extra docs build_docs.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy to gh-pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git rm -rf .
          mv docs/_build/html/* .
          mv docs/_build/html/.nojekyll .
          mv docs/_build/html/.buildinfo .
          rm -rf docs warp _build __pycache__
          git add . .nojekyll .buildinfo
          git commit -m "Deploy Sphinx documentation"
          git push -f origin gh-pages
