# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ==============================================================================
# Warp Kit Extensions Testing and Deployment Child Pipeline
# ==============================================================================

include:
  - /.gitlab/ci/common.yml
  - project: "omniverse/warp-gitlab-ci"
    ref: "main"
    file: "/.gitlab/ci/kit-extensions.yml"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

stages:
  - quality
  - test
  - package
  - deploy

# ==============================================================================
# Shared Configuration & Snippets
# ==============================================================================

# Base configuration for all Kit extension tests
.test-kit-ext-base:
  variables:
    OMNI_KIT_ALLOW_ROOT: "1"
    KIT_DIR: "./_build/kit-deps/kit-kernel"
    TEST_OUTPUT_DIR: "./_testoutput"

# Kit-specific snippets
.kit-snippets:
  prepare-kit-artifacts:
    - uv run --no-project tools/ci/publishing/build_nodes_info.py
    - mv warp exts/omni.warp.core/
    - find . -type f -exec chmod 664 {} +
    - find . -type d -exec chmod 775 {} +
    - find exts/ -name .gitignore -delete
  test-kit-ext-linux-x86_64:
    - mkdir ./_testoutput
    - |
      "${KIT_DIR}/kit" \
        --enable omni.kit.test \
        --enable omni.kit.loop-default \
        --/app/enableStdoutOutput=0 \
        --/exts/omni.kit.test/testExts/0="${TEST_KIT_EXT}" \
        --ext-folder "${KIT_DIR}/exts" \
        --ext-folder "${KIT_DIR}/extscache" \
        --ext-folder "${KIT_DIR}/apps" \
        --/exts/omni.kit.test/testExtOutputPath="./_testoutput" \
        --portable-root "${KIT_DIR}/" \
        --/telemetry/mode=test \
        --/crashreporter/data/testName="ext-test-${TEST_KIT_EXT}" \
        --ext-folder exts
  test-kit-ext-windows-x86_64:
    - mkdir .\_testoutput
    - |
      & "${env:KIT_DIR}\kit.exe" `
        --enable omni.kit.test `
        --enable omni.kit.loop-default `
        --/app/enableStdoutOutput=0 `
        --/exts/omni.kit.test/testExts/0="${env:TEST_KIT_EXT}" `
        --ext-folder "${env:KIT_DIR}/exts" `
        --ext-folder "${env:KIT_DIR}/extscache" `
        --ext-folder "${env:KIT_DIR}/apps" `
        --/exts/omni.kit.test/testExtOutputPath="./_testoutput" `
        --portable-root "${env:KIT_DIR}/" `
        --/telemetry/mode=test `
        --/crashreporter/data/testName="ext-test-${env:TEST_KIT_EXT}" `
        --ext-folder exts

# ==============================================================================
# Quality Checks
# ==============================================================================

check extensions public API:
  stage: quality
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: linux-x86_64 build
  extends:
    - .ipp_lnx_x86_64_cpu_micro
  before_script:
    - !reference [.snippets, setup-packman-config]
    - tools/packman/packman pull -p manylinux_2_35_x86_64 deps/kit-deps.packman.xml
  script:
    - tools/repo.sh checkapi

# ==============================================================================
# Extension Testing Jobs
#
# Tests both omni.warp.core and omni.warp extensions
# ==============================================================================

linux-x86_64 extension omni.warp.core test:
  stage: test
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: linux-x86_64 build
  image:
    name: ${CI_REGISTRY}/omniverse/devplat/terraform/nvks/runners/gpu/nvks-gstreamer:2.1.5
    entrypoint: [""]
  extends:
    - .ipp_lnx_x86_64_gpu
    - .test-kit-ext-base
  before_script:
    - !reference [.snippets, setup-packman-config]
    - tools/packman/packman pull -p manylinux_2_35_x86_64 deps/kit-deps.packman.xml
    - export TEST_KIT_EXT="omni.warp.core"
    - mv warp/bin/linux-x86_64/*.so warp/bin
  script:
    - !reference [.kit-snippets, test-kit-ext-linux-x86_64]
  artifacts:
    name: $CI_JOB_NAME_SLUG
    paths:
      - "./_testoutput"
    expire_in: 1 week
    when: always

windows-x86_64 extension omni.warp.core test:
  stage: test
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: windows-x86_64 build
  extends:
    - .runner-test-windows-x86_64-gpu
    - .test-kit-ext-base
  before_script:
    - Move-Item -Path $env:PACKMAN_CONFIG_FILE -Destination "$env:CI_PROJECT_DIR\tools\packman\config.packman.xml" -Force
    - tools\packman\packman.cmd pull -p windows-x86_64 deps/kit-deps.packman.xml
    - $env:TEST_KIT_EXT = "omni.warp.core"
  script:
    - !reference [.kit-snippets, test-kit-ext-windows-x86_64]
  artifacts:
    name: $CI_JOB_NAME_SLUG
    paths:
      - "./_testoutput"
    expire_in: 1 week
    when: always

linux-x86_64 extension omni.warp test:
  stage: test
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: linux-x86_64 build
  image:
    name: ${CI_REGISTRY}/omniverse/devplat/terraform/nvks/runners/gpu/nvks-gstreamer:2.1.5
    entrypoint: [""]
  extends:
    - .ipp_lnx_x86_64_gpu
    - .test-kit-ext-base
  before_script:
    - !reference [.snippets, setup-packman-config]
    - tools/packman/packman pull -p manylinux_2_35_x86_64 deps/kit-deps.packman.xml
    - export TEST_KIT_EXT="omni.warp"
    - mv warp/bin/linux-x86_64/*.so warp/bin
  script:
    - !reference [.kit-snippets, test-kit-ext-linux-x86_64]
  artifacts:
    name: $CI_JOB_NAME_SLUG
    paths:
      - "./_testoutput"
    expire_in: 1 week
    when: always

windows-x86_64 extension omni.warp test:
  stage: test
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: windows-x86_64 build
  extends:
    - .runner-test-windows-x86_64-gpu
    - .test-kit-ext-base
  before_script:
    - Move-Item -Path $env:PACKMAN_CONFIG_FILE -Destination "$env:CI_PROJECT_DIR\tools\packman\config.packman.xml" -Force
    - tools\packman\packman.cmd pull -p windows-x86_64 deps/kit-deps.packman.xml
    - $env:TEST_KIT_EXT = "omni.warp"
  script:
    - !reference [.kit-snippets, test-kit-ext-windows-x86_64]
  artifacts:
    name: $CI_JOB_NAME_SLUG
    paths:
      - "./_testoutput"
    expire_in: 1 week
    when: always

# ==============================================================================
# Packaging Jobs
# ==============================================================================

# Creates an artifact suitable for publishing the Kit extensions
create linux-aarch64 kit artifacts:
  stage: package
  image: $UV_TRIXIE_SLIM_IMAGE
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: linux-aarch64 build
  extends:
    - .ipp_lnx_x86_64_cpu_micro
  before_script:
    - !reference [.snippets, move-linux-aarch64-binaries]
  script:
    - !reference [.kit-snippets, prepare-kit-artifacts]
    - uv run --no-project python -m zipfile -c kit-extensions-linux-aarch64-$CI_COMMIT_SHORT_SHA.zip exts/
  artifacts:
    name: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expose_as: "Kit Extensions linux-aarch64"
    paths:
      - kit-extensions-linux-aarch64-$CI_COMMIT_SHORT_SHA.zip

create linux-x86_64 kit artifacts:
  stage: package
  image: $UV_TRIXIE_SLIM_IMAGE
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: linux-x86_64 build
  extends:
    - .ipp_lnx_x86_64_cpu_micro
  before_script:
    - !reference [.snippets, move-linux-x86_64-binaries]
  script:
    - !reference [.kit-snippets, prepare-kit-artifacts]
    - uv run --no-project python -m zipfile -c kit-extensions-linux-x86_64-$CI_COMMIT_SHORT_SHA.zip exts/
  artifacts:
    name: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expose_as: "Kit Extensions linux-x86_64"
    paths:
      - kit-extensions-linux-x86_64-$CI_COMMIT_SHORT_SHA.zip

create windows-x86_64 kit artifacts:
  stage: package
  image: $UV_TRIXIE_SLIM_IMAGE
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: windows-x86_64 build
  extends:
    - .ipp_lnx_x86_64_cpu_micro
  script:
    - !reference [.kit-snippets, prepare-kit-artifacts]
    - uv run --no-project python -m zipfile -c kit-extensions-windows-x86_64-$CI_COMMIT_SHORT_SHA.zip exts/
  artifacts:
    name: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expose_as: "Kit Extensions windows-x86_64"
    paths:
      - kit-extensions-windows-x86_64-$CI_COMMIT_SHORT_SHA.zip

# ==============================================================================
# Deployment Jobs
# ==============================================================================

# Uploads the extension artifacts to the internal GitLab package registry
publish to gitlab package registry:
  stage: deploy
  image: $UV_TRIXIE_IMAGE
  needs:
    - create linux-aarch64 kit artifacts
    - create linux-x86_64 kit artifacts
    - create windows-x86_64 kit artifacts
  extends:
    - .ipp_lnx_x86_64_cpu_micro
  rules:
    - if: $PARENT_COMMIT_TAG
    - when: manual # Can be triggered in all other scenarios
      allow_failure: true
  script:
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file kit-extensions-linux-aarch64-$CI_COMMIT_SHORT_SHA.zip
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/warp/${CI_COMMIT_REF_SLUG}/kit-extensions-linux-aarch64-${CI_COMMIT_SHORT_SHA}.zip"
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file kit-extensions-linux-x86_64-$CI_COMMIT_SHORT_SHA.zip
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/warp/${CI_COMMIT_REF_SLUG}/kit-extensions-linux-x86_64-${CI_COMMIT_SHORT_SHA}.zip"
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file kit-extensions-windows-x86_64-$CI_COMMIT_SHORT_SHA.zip
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/warp/${CI_COMMIT_REF_SLUG}/kit-extensions-windows-x86_64-${CI_COMMIT_SHORT_SHA}.zip"
    - echo "See the published files at $CI_PROJECT_URL/-/packages"
